import Head from 'next/head'
import React, { useContext, useState } from 'react';
import AuthContext from '@/context/authContext';

export default function Home() {
  const { user } :any = useContext(AuthContext)
  return (
    <>
      <Head>
        <title>Raf Yönetimi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <span className='text-xl'>Hoş Geldin <span className='text-green-600'>{user?.username}</span>. İşlemlerine sol menüden devam edebilirsin.</span>
      </main>
    </>
  )
}